### PR TITLE
avoid redirection

### PR DESCRIPTION
**Pull request by ma2gedev**
:metal:

### CODE REVIEW

**Comment by shuhei** [comment]
LTGM 😄  It looks like I'm still in the org.

**Comment by ma2gedev** [comment]
@shuhei Oops! I'd like to confirm though you are welcome IMO. 😄

**Comment by btakashi** [comment]
@shuhei Hey how's it going... Hope you are doing well in Germany. I will remove you from the org...

**Comment by shuhei** [comment]
Thanks! I should have left the org by myself. It's cold here in Berlin, but people, food and of course beer are nice. I'm still in a onboarding bootcamp at the company and I'll pick a team to join at the end of this month.

**Pull request merged**
